title:            dinghing
description:      Love life
url:              http://dinghing.github.io
signoff:          dinghing
disqus_shortname: dinghing
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.
gems:
  - jekyll-seo-tag
google_site_verification:dfGACJLdxt3bAsd-QwrXG0TJ3NzO8rzE1dMrZxD9aAU

links:
  - name:         About me
    url:          https://dinghing.github.io/aboutme
    external:     true
  - name:         Home
    url:          /
  - name:         Blog(old)
    url:          http://www.cnblogs.com/dinghing154/
    external:     true
  - name:         GitHub
    url:          http://github.com/dinghing
    external:     true
  - name:         Artist
    url:          /artist/artist
    external:     true   
highlighter:      rouge
permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
