title:            dinghing
signoff:          dinghing
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          http://www.mymunan.com/2016/aboutme 
  - name:         Blog
    url:          http://www.cnblogs.com/dinghing154/
    external:     true
  - name:         GitHub
    url:          http://github.com/dinghing
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
